/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package terminalrpg;

/**
 * Main entry into the program, will be run with gradle run command.
 */
public class App {

    
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
